services:
  mongodb:
    image: mongo:7.0
    container_name: careflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-careflow}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
    container_name: careflow-server
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      MONGO_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/${MONGO_DB:-careflow}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-this-in-production}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb-data:
